### ISSUE TITLE
Feature request - ability to kill daemons

### ISSUE THREAD

**Issue by kegobass** [infernoboy/Temporary-Background-Spawn#2]
Hi. Any chance you could expand this tweak to kill daemons?  Thanks.

**Comment by infernoboy** [comment]
This tweak is specifically written to work only for apps. Daemons are an entirely different scenario. They are either on-demand or always running, and typically consume minimal memory. Killing a daemon will most likely make it re-spawn automatically because iOS needs it running. Even for the on-demand ones that won't instantly relaunch, there's really no way to determine if it's safe to kill at any given moment.
